### ISSUE TITLE
Hello Tiago. Could you please reopen this issue as it is not solved. Version 16 already exists but not in repository

### ISSUE THREAD

**Issue by omega69** [tproenca/pmsarm7#11]
Hello

There is newer version available on Plex server. Is there any plan to update this repo or it is already dead? My understanding (may be wrong) is this package update is done automatically when Plex file is updated.

Thanks for feedback

**Comment by tproenca** [comment]
I fixed the script that was parsing the plexmediaserver binaries from plex.tv webpage. The build is working now.

**Comment by omega69** [comment]
Unfortunately new update is available on plex site but no update in your repository. Looks like solution was not working properly

**Comment by omega69** [comment]
Hello Tiago

Could you please reopen this issue as it is not solved. Version 16 already exists but not in repository
